sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

install:
  - npm install
  - npm install -g vsce typescript
  - npm run compile
  - vsce package
  - npm run test
  
deploy:
  - provider: script
    script: cp ./src/pslLint/cli/.npmrc.psl-lint .npmrc && npm pack ./src/pslLint/cli | xargs npm publish
    on:
      tags: true
      condition: tag =~ ^psl-lint
  - provider: script
    script: vsce publish -p $VSCODE
    on:
      tags: true
      condition: tag =~ ^vscode-psl
