sudo: false
dist: trusty

language: node_js

# https://docs.travis-ci.com/user/build-stages/deploy-npm/
node_js:
  - "10.12.0"

jobs:
  include:
    - stage: TS Compile to JS
      script:
        - npm run compile
        - npm run compile-lint

    - stage: Check quality
      script:
        - npm run linter

    - stage: Run tests
      script:
        - npm run test
 
deploy:
  - provider: script
    script: cp ./src/pslLint/cli/.npmrc.psl-lint .npmrc && npm pack ./src/pslLint/cli | xargs npm publish
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^psl-lint
      all_branches: true
      repo: ing-bank/vscode-psl
  - provider: script
    script: vsce publish -p $VSCODE_TOKEN
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^vscode-psl
      all_branches: true
      repo: ing-bank/vscode-psl
