language: node_js

# https://docs.travis-ci.com/user/build-stages/deploy-npm/
node_js:
  - "8.9.4"

jobs:
  include:
    - stage: TS Linter
      script:
        - echo "Run TS linter ..."
        - npm install tslint typescript -g
        - tslint -c tslint.json --project .

    - stage: Run tests
      script:
        - echo "Run tests ..."
        - npm run test

    - stage: Publish Extension
      if: branch = master
      script:
        - echo "Publish Extension (only for master) ..."
        - npm install -g vsce
        - vsce publish
