sudo: false
dist: trusty
language: node_js
node_js:
  - "10"

stages:
  - Build
  - name: Deploy lint
    if: repo = ing-bank/vscode-psl AND tag =~ ^lint
  - name: Deploy vscode
    if: repo = ing-bank/vscode-psl AND tag =~ ^vscode

jobs:
  include:
    - stage: Build
      script:
        - npm run compile
        - npm run compile-lint
      name: Compile
    - script:
        - npm run linter
      name: Lint
    - script:
        - npm run test
      name: Test

    - stage: Deploy lint
      script: cp ./src/pslLint/cli/.npmrc.psl-lint .npmrc && npm run compile-lint && npm pack ./src/pslLint/cli | xargs npm publish
      name: npm
    
    - stage: Deploy vscode
      script: npm run compile && npm i -g vsce && vsce package && vsce publish -p $VSCODE_TOKEN
      name: marketplace
