language: node_js

# https://docs.travis-ci.com/user/build-stages/deploy-npm/
node_js:
  - "10.12.0"

jobs:
  include:
    - stage: TS Compile to JS
      script:
        - npm run compile
        - npm run compile-lint

    - stage: Check quality
      script:
        - npm run linter

    - stage: Run tests
      script:
        - npm run test
